source "https://rubygems.org"
gem "bundler", "~> 2.7"
gem "jekyll-theme-h2o-ac", "~> 1.5"
gem "jekyll-paginate-v2", "~> 3.0"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-sitemap", "~> 1.4"
gem "premonition", "~> 4.0"
gem "h2o-ac-jekyll-extlinks", "~> 0.0"
gem "webrick", "~> 1.8"
